name: courtwala
description: A sports booking app for badminton, padel, cricket, and football courts.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^2.23.0
  firebase_auth: ^4.7.0
  js: ^0.7.2
  google_sign_in: ^6.1.5
  carousel_slider: ^5.1.0
  font_awesome_flutter: ^10.4.0
  fl_chart: ^0.66.0
  image_picker: ^1.1.1
  intl: ^0.18.1
  http: ^1.2.0
  shared_preferences: ^2.2.2
  http_parser: ^4.0.2
  url_launcher: ^6.2.1
  app_links: ^6.4.1
  cached_network_image: ^3.4.0
  timeago: ^3.7.1
  video_player: ^2.11.1
  chewie: ^1.13.1
  video_thumbnail: ^0.5.6
  path_provider: ^2.1.5



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

  # 🔑 App launcher icon generator
  flutter_launcher_icons: ^0.13.1

# 🔑 Flutter launcher icon configuration
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/CW.png"
  adaptive_icon_background: "#E7E5D7"
  adaptive_icon_foreground: "assets/CW.png"
  min_sdk_android: 21
  remove_alpha_ios: true

flutter:
  uses-material-design: true

  assets:
    - assets/CW.png
    - assets/welcome.png
    - assets/role selection.png
    - assets/forgot.png
    - assets/900W-90-flood-light-illuminate-tennis-court.jpg
    - assets/black-gradient-football-field-background-inst-design-template-45f0c6eea75ea829f5e7bee1347353fc_69e643f6-94f5-4963-a199-c6198e51ae93_screen.png
    - assets/tt-1724319499860.webp

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
        - asset: assets/fonts/Poppins-SemiBold.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
        
