-- AlterTable
ALTER TABLE `Notification` MODIFY `type` ENUM('BOOKING_REQUESTED', 'BOOKING_APPROVED', 'BOOKING_REJECTED', 'BOOKING_CANCELLED', 'MATCH_REQUEST', 'MATCH_ACCEPTED', 'MATCH_REJECTED', 'COURT_APPROVED', 'COURT_REJECTED', 'OWNER_APPROVED', 'OWNER_REJECTED', 'ADMIN_ANNOUNCEMENT', 'TOURNAMENT_JOINED', 'REPORT_RESOLVED') NOT NULL;
